AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru

require:
  - rubocop-rspec

RSpec/EmptyExampleGroup:
  Enabled: false